name: Coffee Cloud Client Application Form
description: Coffee Cloud Application
title: "[CoffeeCloud Client Applicaiton]: "
labels: ["data cap", "client app.", "filecoin"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filling out CoffeeCloud Client Application Form!
  - type: input
    id: Name
    attributes:
      label: Name
      description: What is your name?
      placeholder: ex. John Smith
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: input
    id: github
    attributes:
      label: GitHub Account
      description: Do you have a you GitHub account?
      placeholder: https://github.com/coffee-cloud-project/
    validations:
      required: false 
  - type: input
    id: oldest_social_media
    attributes:
      label: Oldest Social Media Account
      description: What is your oldest Social Media Account?
      placeholder: https://www.facebook.com/Coffee-Cloudio
    validations:
      required: false
  - type: input
    id: date_social_media
    attributes:
      label: Date Social Media Account
      description: When Was Your Social Media Account Created?
      placeholder: 1st April, 2020
    validations:
      required: false
  - type: dropdown
    id: asia_pacific
    attributes:
      label: Are you located in the Asia Pacific region?
      multiple: true
      options:
        - "Yes"
        - "No"
  - type: input
    id: country
    attributes:
      label: Country 
      description: Where are your or your organization located?
      placeholder: ex. Spain
    validations:
      required: true
  - type: dropdown
    id: individual_or_organization
    attributes:
      label: Are you applying as a individual or an organization?
      multiple: true
      options:
        - "Individual"
        - "Organization"
  - type: input
    id: company_name
    attributes:
      label: Organization / Company Name 
      description: What is your organization or Company name?
      placeholder: ex. Coffee Cloud Ltd.
    validations:
      required: false
  - type: input
    id: Number_of_employees
    attributes:
      label: Number of Employees
      description: How many employees do you have?
      placeholder: ex. 25 Employees
    validations:
      required: false
  - type: textarea
    id: Press_Coverage
    attributes:
      label: Can you provide any recent Press coverage?
      description: Can you provide any articles, videos or recent press coverage?
      placeholder: Press Coverage from BBC - https://www.bbc.co.uk/sounds/play/w3cszcp7
      value: 
    validations:
      required: false
  - type: textarea
    id: Web_Links
    attributes:
      label: Can you provide links to any related websites?
      description: Please provide links to any related websites or blogs.
      placeholder: Website - https://coffeecloud.io/#/home  Blog - https://coffeecloudblog.io/
      value: 
    validations:
      required: false
  - type: input
    id: Filecoin_Address
    attributes:
      label: Filecoin Address
      description: Please provide your Filecoin Address
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: Past_Projects
    attributes:
      label: Can you provide any details on past projects?
      description: Please provide any relevent details on past projects (please include links if available) 
      placeholder: We work previously on a Filecoin project - www.filecoinproject.com
      value: 
    validations:
      required: false
  - type: textarea
    id: Data_Format
    attributes:
      label: What is the data? What is the Format?
      description: Please describe which the format of the data (video, audio, information, etc.)
      placeholder: My project is a video format in MP4.
      value: 
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
